#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $oom_config_screen_on;
else
	oom_config_screen_on=$2;
	echo "$oom_config_screen_on";
fi;

PROFILE=`cat /data/.siyah/.active.profile`;
AUTO_OOM=`cat /data/.siyah/${PROFILE}.profile | grep auto_oom=on | wc -l`

if [ "$AUTO_OOM" -eq "1" ]; then
	case "${oom_config_screen_on}" in
		low)
			echo "12288,15360,18432,21504,24576,20480" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		medium)
			echo "12288,15360,18432,21504,24576,20480" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		default)
			echo "12288,15360,18432,21504,24576,30720" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "18432,23040,27648,34816,51200,65536" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "18432,23040,27648,53760,58880,65536" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			oom_config_screen_on=medium;
		;;
	esac;
fi;
