#!/sbin/busybox sh

/sbin/busybox mount -o remount,rw /;
echo "START" > /tmp/trim_part;
chmod 777 /tmp/trim_part;

(
	echo "Trim CACHE Partition" >> /tmp/trim_part;
	/sbin/fstrim -v /cache  >> /tmp/trim_part;	
	
	echo "Trim System Partition" >> /tmp/trim_part;
	/sbin/fstrim -v /system  >> /tmp/trim_part;
	
	echo "Trim DATA Partition" >> /tmp/trim_part;
	/sbin/fstrim -v /data  >> /tmp/trim_part;
	
	echo "Trim Preload Partition" >> /tmp/trim_part;
	/sbin/fstrim -v /preload  >> /tmp/trim_part;
	
	echo "All-Done" >> /tmp/trim_part;
)&

while [ ! `cat /tmp/trim_part | grep "All-Done" | wc -l` == "1" ]; do
	sleep 2;
done;
TRIM_LOG=`cat /tmp/trim_part`;
echo "$TRIM_LOG";